require 'octokit'

module Snitch
  class ExternalServiceAdapter
    def initialize(repository, access_token)
      @repo, @service = repository, new_service(access_token)
    end

    def list_issue_names
      @service.list_issues(@repo, state: 'open').map(&:title)
    end

    def create_issue(example)
      title = example.full_description
      body = "#{example.location}\n\nThis issue was generated by rspec-snitch."
      @service.create_issue(@repo, title, body)
    end

    private

    def new_service(access_token)
      Octokit::Client.new(access_token: access_token)
    end
  end
end
