require 'spec_helper'

describe RspecSnitch::PendingReporter do
  describe 'pending examples' do
    let(:config)   { instance_double "RSpec::Core::Configuration" }
    let(:reporter) { instance_double "RSpec::Core::Reporter",
                     pending_examples: examples }
    let(:service)  { instance_double "Octokit::Client",
                     list_issues: [], create_issue: true }
    let(:snitch)   { RspecSnitch::PendingReporter.new config,
                     repository: 'example repo', access_token: 'exampletoken' }

    before(:each) do
      config.instance_variable_set(:@reporter, reporter)
      allow_any_instance_of(RspecSnitch::ExternalServiceAdapter).
        to receive(:new_service).and_return(service)
    end

    context 'user wants report' do
      before(:each) { allow_any_instance_of(RspecSnitch::PendingReporter).
                      to receive(:user_wants_report?).and_return(true) }

      context '2 pending examples ' do
        let(:examples) { [double(pending?: true, full_description: 'first title',
                          location: 'my location'),
                          double(pending?: true, full_description: 'second title',
                          location: 'my location')] }

        before(:each) do
          expect(service).to receive(:create_issue).once.
            with 'example repo', 'first title',
            "my location\n\nThis issue was generated by rspec-snitch."
          expect(service).to receive(:create_issue).once.
            with 'example repo', 'second title',
            "my location\n\nThis issue was generated by rspec-snitch."
        end

        after(:each) { snitch }

        it 'should create two issues if two pending example' do
        end

        it 'should not create multiple issues of same spec' do
          snitch
        end
      end

      context 'no pending examples' do
        let(:examples) { [double(pending?: false, full_description: 'first title',
                          location: 'my location')] }

        it 'should not create issue' do
          expect(service).to_not receive(:create_issue)
          snitch
        end
      end
    end

    context 'user does not want report' do
      let(:snitch)   { RspecSnitch::PendingReporter.new config,
                      repository: 'example repo', ask: false,
                      access_token: 'exampletoken' }
      let(:examples) { [double(pending?: true, full_description: 'first title',
                        location: 'my location')] }

      it 'should not create issue' do
        expect(service).to_not receive(:create_issue)
        snitch
      end
    end
  end
end
