require "rspec_snitch/version"
require 'octokit'

module RspecSnitch

  def self.new(*args)
    Snitch.new(*args)
  end

  class Snitch

    def initialize(access_token, repo, config)
      @github       ||= Octokit::Client.new(access_token: access_token)
      @issue_titles ||= @github.list_issues(repo, state: 'open').map(&:title)
      @examples     ||= config.instance_variable_get(:@reporter)
      generate_issues
    end

    def generate_issues
      pendings = @examples.pending_examples
      @reportable_examples = pendings.keep_if do |example|
        example.pending? && @issue_titles.exclude?(example.full_description)
      end
      ask_question
    end

    def ask_question
      thor = Thor::Shell::Basic.new
      question = "#{pluralize(reportable_examples.size, 'issue')} to report. Snitch to GitHub? (y/n):"
      report_examples if @reportable_examples.any? && thor.yes?(question)
    end

    def report_examples
      @reportable_examples.each do |example|
        title = example.full_description
        body = "#{example.location}\n\nThis issue was generated by rspec-snitch."
        @github.create_issue(repo, title, body)
        # TODO: Reopen issue if one exists, but is closed.
      end
    end
  end
end
